const LOGOUT = 'LOGOUT'

const LOGIN_START = 'LOGIN_START'
const LOGIN_END = 'LOGIN_END'

const READ_POSTS_START = 'READ_POSTS_START'
const READ_POSTS_END = 'READ_POSTS_END'

export { 
  LOGOUT, 
  LOGIN_START, 
  LOGIN_END, 
  READ_POSTS_START, 
  READ_POSTS_END 
}